# https://taskfile.dev
# to install ˋtaskˋ
# go install github.com/go-task/task/v3/cmd/task@latest

version: '3'

vars:
  FOLDER: "files"

tasks:
  run:
    cmds:
      - go run main.go {{ .FOLDER }}/{{.CLI_ARGS}}.json
  
  rinha:
    cmds:
      - rinha {{.FOLDER}}/{{.CLI_ARGS}}.rinha | jq > {{.FOLDER}}/{{.CLI_ARGS}}.json

  build:
    cmds:
      - go build -o ./bin/gorinha .
  
  docker-build:
    cmds:
      - docker build -t gorinha .
  
  docker-run:
    cmds:
      - docker run gorinha files/{{.CLI_ARGS}}.json

  test:
    cmds:
      - go test
